### ISSUE TITLE
share/zeekctl/scripts/zeekctl-config.sh link must be relative

### ISSUE THREAD

**Issue by 0xxon** [zeek/zeekctl#31]
Zeekctl currently always creates a link from ``share/zeekctl/scripts/zeekctl-config.sh`` to ``../../../spool/zeekctl-config.sh``. That link must be a relative link. Zeekctl will delete and recreate the link when it is an absolute link pointing to the same file.

For packaging purposes it would be great if zeekctl could just also accept an absolute link pointing to the same location.

More details:

When creating a binary package, relative links are forbidden in the package by virtually all distributions.

When the Zeek installation aims to be usable by a non-root-user, it is pretty inconvenient to make the ``share/zeekctl/scripts/zeekctl-config.sh`` changeable by everyone (the directory needs to be writeable by the user who runs zeekctl to enable that - which seems not great).

**Comment by jsiwek** [comment]
> When the Zeek installation aims to be usable by a non-root-user, it is pretty inconvenient to make the `share/zeekctl/scripts/zeekctl-config.sh` changeable by everyone (the directory needs to be writeable by the user who runs zeekctl to enable that - which seems not great).

Not sure that part is (easily) avoidable: regardless of whether the link is relative vs. absolute, the `SpoolDir` is changeable by users in `zeekctl.cfg` and the link needs to be recreated by `zeekctl` if it does change, right?

> For packaging purposes it would be great if zeekctl could just also accept an absolute link pointing to the same location.
> 
> More details:
> 
> When creating a binary package, relative links are forbidden in the package by virtually all distributions.

The relative-ness of it was requested in #22 (interesting contradiction in package/port requirements that I don't understand).

So thinking that if a package installed it as absolute or even installed nothing at all (`zeekctl` seems fine with creating it if it's absent), that still may not ultimately solve the potential for permission/user issues due to recreating the link (on config/dir changes).

**Comment by 0xxon** [comment]
I am just going to close this - I am not even sure this is a problem anymore; if it is, our packages work around it.
